apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-chart.fullname" . }}-config
data:
  USER: {{ .Values.user | quote }}
  MYSQL_HOST: {{ .Values.database.mysqlHost | quote }}
  MYSQL_USER: {{ .Values.database.mysqlUser | quote }}
  MYSQL_DB: {{ .Values.database.mysqlDb | quote }}
  MYSQL_TABLE: {{ .Values.database.mysqlTable | quote }}
  API_BASE_URL: {{ .Values.apiBaseUrl | quote }}
